[package]
name = "relox"
version = "0.1.0"
edition = "2021"
authors = ["Michael Fisher mifi@hey.com"]
license-file = "LICENSE.txt"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
