on:
  push:
    branches:
      - main

name: Release Packaging

jobs:
  release:
    name: Release Packaging
    env:
      PROJECT_NAME_UNDERSCORE: relox
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@stable

      - name: Release Build
        run: cargo build --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PROJECT_NAME_UNDERSCORE }}
          path: target/release/${{ env.PROJECT_NAME_UNDERSCORE }}
