on:
  push:
    branches:
      - main

name: Release Packaging

jobs:
  linux:
    name: Release Packaging for Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@stable

      - name: Release Build
        run: cargo build --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: relox-x86_64-unknown-linux-gnu
          path: target/release/relox

  windows:
    name: Release Packaging for Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-gnu

      - name: Release Build
        run: cargo build --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: relox-x86_64-pc-windows-gnu.exe
          path: target/release/relox.exe

  macos:
    name: Release Packaging for MacOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin

      - name: Release Build
        run: cargo build --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: relox-aarch64-apple-darwin
          path: target/release/relox
